// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// pnpm prisma generate -> pnpm prisma db push
// pnpm dlx prisma db seed
// pnpm prisma migrate reset

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "database/prisma/schema.prisma",
  migrations: {
    path: "database/prisma/migrations",
    seed: "tsx database/prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
